### ISSUE TITLE
CMake generation fails to find Arduino SDK path

### ISSUE THREAD

**Issue by MrPointer** [JonasProgrammer/arduino-cmake#6]
## Background
A while ago I've setup my work computer (Completely offline) to work with this fork, installing **Arduino 1.8.1** complete SDK, **CMake 3.82**, **mingw-64** as my build system and **CLion** as my IDE ***On a Windows machine***. 
  
## Issue
Unfortunately, the very first **CMake** generation has failed, yelling at me that it couldn't find `Arduino's SDK path`, which was strange. At first I though it had something to do with **CLion**, so I tried to generate it simply with **cmake-gui**, but, with no success either.  
  
## Capturing the bug
After a few days of occasional debugging, I came to a conclusion that the problem is indeed with my `SDK path`, or more accurately, where I've set it.  
Due to some reasons I had to install **Arduino** on my `D:\` drive - To put in other words, my first ever attempt to install it on something other than the casual `C:\Program Files\`. I really suspect that this might be the source of the bug, with our **CMake** script not being able to handle something other than the default, casual path.  
However, I didn't had time yet to pursue the issue and fix the bug.

## Fix is on the way
No, there is no solution yet, but I'm working on it now as I have a bit more time to address it.  
Would be glad to see someone else also attempt to solve it though!

### No logs attached
Unfortunately, I don't have any logs that I can attach here, simply because it happened only at my work computer, which is, as I stated earlier, completely offline, and I can't export anything out of the work.

**Comment by JonasProgrammer** [comment]
Well, I haven't tested anything with a 1.8 SDK so far, but on both of my development machines the SDK is installed to a nonstandard location on another drive, so this shouldn't be an issue.

Have you set the ARDUINO_SDK_PATH environment variable to hint the SDK path for prior to generation?

**Comment by MrPointer** [comment]
@JonasProgrammer Yes, I did set the variable to the appropriate path.
I'm currently working on setting up a clean VM to investigate this further.

P.S.
Can you please respond to the email I've sent you privately? Thanks.

**Comment by JonasProgrammer** [comment]
See https://github.com/arduino-cmake/arduino-cmake/issues/2
