### ISSUE TITLE
USB VID and PID for CDC

### ISSUE THREAD

**Issue by Baycken** [JonasProgrammer/arduino-cmake#9]
I would like to implement custom VID and PID for USB CDC. I need this for the udev rules to distinguish multiple Arduino Leonardo connected to my robotics system.

The other option is to properly implemented the iSerial of the CDC, but that requires chances in the source code of arduino core which I think is more difficult.

Basically this involve adding some if statement in [here](https://github.com/JonasProgrammer/arduino-cmake/blob/master/cmake/Platform/Arduino.cmake#L2275).

And maybe add a PID and VID argument in `generate_arduino_firmware`.

I think I have an idea how to do this, just want to make sure that you think this is useful before I start to work on this.

**Comment by JonasProgrammer** [comment]
While I agree that this would be useful for boards with on-chip usb support, I'm not quite sure how this works out with Uno and all the other boards that use a separate communication device. Well yes, you could also ISP-flash that thing with a custom firmware (at least for the Uno revisions that use a Mega8 for usb comm), but that would be separate from the main firmware.

Skimming over boards.txt I currently also see no way to easily determine whether a board supports custom VIDs/PIDs.

Don't get me wrong, I think the feature itself is quite useful. I'm just a bit concerned of adding more options to generate_arduino_firmware that only work on specific boards.

Perhaps we could make a generate_arduino_firmware_ex or something which allows more customization but officially 'without any warranty' and with a 'only use it when you're 100% sure what you're doing' disclaimer.

But that's just my oppinion. We've moved the project to https://github.com/arduino-cmake/arduino-cmake
Perhaps we could re-open this there and see what @MrPointer & co. think?

**Comment by Baycken** [comment]
https://github.com/arduino-cmake/arduino-cmake/issues/4
